[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
basis_vault = "GLfySZNLkrDGLmckY1vpFEiXxHToMJzPtCWQcx4wDgbS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
